{% set name = "confuse" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7379a2ad49aaa862b79600cc070260c1b7974d349f4fa5e01f9afa6c4dd0611f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
    - flit-core >=2,<4
  run:
    - python
    - pyyaml

test:
  source_files:
    - test
  imports:
    - confuse
  requires:
    - pip
    - pytest
  commands:
    - pip check
    # E   OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect
    - pytest test -k "not (test_create_dir_if_none_exists or test_do_not_create_dir_if_lower_priority_exists or test_return_existing_dir)" # [win]
    - pytest test # [not win]

about:
  home: https://github.com/beetbox/confuse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: painless YAML configuration
  description: |
    Confuse is a configuration library for Python that uses YAML.
    It takes care of defaults, overrides, type checking, command-line
    integration, human-readable errors, and standard OS-specific locations.
  doc_url: https://confuse.readthedocs.org
  dev_url: https://github.com/beetbox/confuse

extra:
  recipe-maintainers:
    - philip-khor
