{% set name = "confuse" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0bab4c2e1209d2a7d28f7634e735f5f8e46f561556186951377511f1714cca1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyyaml

test:
  imports:
    - confuse

about:
  home: https://github.com/beetbox/confuse
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: painless YAML configuration

  description: |
    Confuse is a configuration library for Python that uses YAML.
    It takes care of defaults, overrides, type checking, command-line
    integration, human-readable errors, and standard OS-specific locations.
  doc_url: http://confuse.readthedocs.org/
  dev_url: https://github.com/beetbox/confuse

extra:
  recipe-maintainers:
    - philip-khor
