travis:
  secure:
    BINSTAR_TOKEN: k99eGHZCZXoaC9aT2C/8LsalCj/Edh/uPnOlxywtUlN2dRBK4VRDFoqPknTIqwxWfo99wYcOhakLfZ4reUH0r7aV25vFwvF/qgwKIISWjLY0IikNivksTC26lgFFMYcDpEX9IakHuIsmEu4ABPnGSxeb4KJG0GpZWcX4/4t8MGPrj3FnA9aXG+/aPabeBnYOhJQsGkaVc9gHnJ0UuB0rWdCK6b3h90gaUiJyyWRlZW0QRzbtj/RsRFjqSXnq43PvxXGrZ77A+QymPBZoJ9FbxS4F5GSs595g77YGttVpARNDzxxKbP+mRkcgeatLNBYB8oB3TJd5YA1GoVFhrigTnzpc4bTnHEVda1+GxKdQQ7fbdTL5c2bF/e0GNzq4vFaU+EpxeC4bXW7c5mTZFzpchnqB3M/ljxte/bu/N542pDm9Gx3jqh4OG4tGs3gYDs92GyDAHE+keLFpnQU48c4duHNrB0+yh20FN8QnW/mV8a88zD7MJ6k9pGRM53hWEVr9rIB7peHIdQnDsFTHnxROO3N60FNmVtFaR6erNY1vGBLWbMWVcpbvGCjWJjwxDYXV297tJKrOS/IkQ7/1aQtPYuegBRw1/FNhuT6bBe+QP+sSrl2SNU6Ljm8UsOZoPweWEiZ1OTaQXRMq6fShOWqZ5Zd2xZbysPG3d/PLX4MjK34=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
